spring:
  application:
    name: api-Gateway
  cloud:
    gateway:
      routes:
        - id: me
          uri: http://localhost:8082/me
          predicates:
            - Path=/me/**
        - id: resource
          uri: http://localhost:9090/resource
          predicates:
            - Path=/resource/**
server:
  port: 8085
