server:
  port: 8081
  servlet:
    context-path: /ui3
spring:
  application:
    name: api-Gateway
  cloud:
    gateway:
      routes:
      - id: me
        uri: http://localhost:8080/me/
        predicates:
        - Path=/me/**
      - id: resource
        uri: http://localhost:8080/me/
        predicates:
        - Path=/resource/**
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"